CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE DATABASE iam;
CREATE DATABASE food;
CREATE DATABASE category;

GRANT ALL PRIVILEGES ON DATABASE iam TO oeuser;
GRANT ALL PRIVILEGES ON DATABASE food TO oeuser;
GRANT ALL PRIVILEGES ON DATABASE category TO oeuser;