server:
  port: 8080
  name: customer

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/food
    username: oeuser
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui
    show-extensions: true
    show-common-extensions: true
  api-docs:
    path: /v3/api-docs/valami