package hu.oe.takeout.entity;
// Generated by Hibernate Tools 6.6.13.Final



import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;


            @lombok.Builder @lombok.AllArgsConstructor @lombok.NoArgsConstructor @lombok.Getter @lombok.Setter @lombok.experimental.FieldNameConstants
        @Entity
        @Table(name="category"
)
public class Category  implements java.io.Serializable {


        
                @jakarta.persistence.GeneratedValue(generator = "uuid-hibernate-generator")
            
                @Id 

           
           @Column(name="id", unique=true, nullable=false)

    private UUID id;
        

           
           @Column(name="name", nullable=false, length=255)

    private String name;
        

        @OneToMany(fetch=FetchType.LAZY, mappedBy="category")
    private Set<Takeout> takeouts = new HashSet<Takeout>(0);





    }
